dist: focal
language: python
os: linux

before_install:
  - curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
  - sudo apt-get install -y rsync minify nodejs
  - pip install -r requirements.txt
  - npm install

install:
  - ./update.sh

before_script:
  - ./.exporter/import_check.sh
  - ./.exporter/check_plz_against_database.py
  - ./.download/prepare.sh # This needs to be done before the exporters run
  - $(npm bin)/gulp compile
  - ./generator.py --loglevel INFO --source $HOME/auskunftsbegehren_at_adressen
  - $(npm bin)/gulp subresource-integrity

script:
  - ./.exporter/exporter.sh
  - ./.exporter/export_check.sh

after_success:
  - find upload/ -type f -name "*.html" -exec minify {} --type html -o {} \;
  - find upload/ -type f -name "*.html" -exec echo "{}" \; -exec $(npm bin)/html-validator --file={} \;

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: $TRAVIS_BUILD_DIR/upload
  strategy: git
  edge: true
  target_branch: gh-pages
  fqdn: auskunftsbegehren-adressen.cyber-perikarp.eu
  committer_from_gh: true
  on:
    branch: main
